### ISSUE TITLE
openai_api_key

### ISSUE THREAD

**Issue by danielgontz** [M1kep/ComfyUI-KepOpenAI#1]
Hello, 
great idea for the plugin. 
but to make our lives easier, is it possible to define the open_api_key somewhere in a file instead of env variable?
Thank you

**Comment by EricRollei** [comment]
This node won't install for me. I'm posting to this issue instead of creating a separate one because I also think a config file is a good way to go.  However  I created the environment variable as you suggested and am using the same key I created for the Omar Quality of Life nodes (he uses a config.json to store the API key btw).

Did I name it correctly?   I don't think I need to restart my computer for this to be seen, and only need to restart Comfy?

![image](https://github.com/M1kep/ComfyUI-KepOpenAI/assets/97568200/039de57e-0d50-4a42-b9c0-3615edb24847)

Here's the console log also:
Traceback (most recent call last):
  File "A:\Comfy_Aug\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "A:\Comfy_Aug\ComfyUI\custom_nodes\ComfyUI-KepOpenAI\__init__.py", line 1, in <module>
    from .nodes import ImageWithPrompt
  File "A:\Comfy_Aug\ComfyUI\custom_nodes\ComfyUI-KepOpenAI\nodes.py", line 4, in <module>
    from openai import Client as OpenAIClient
ImportError: cannot import name 'Client' from 'openai' (A:\Comfy_Aug\python_embeded\Lib\site-packages\openai\__init__.py)

Cannot import A:\Comfy_Aug\ComfyUI\custom_nodes\ComfyUI-KepOpenAI module for custom nodes: cannot import name 'Client' from 'openai' (A:\Comfy_Aug\python_embeded\Lib\site-packages\openai\__init__.py)

**Comment by EricRollei** [comment]
I got this to work on  my end, so all good thanks.

**Comment by eg0pr0xy** [comment]
How did you get it to work? I have the same problem. Thanks!
